# media-wiki-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
spec:
  selector:
    matchLabels:
      app: mediawiki
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      #volumes:
        #- name: config-volume
          #configMap:
            #name: mediawiki-localsettings
      containers:
        - name: mediawiki
          image: mediawiki:latest
          #volumeMounts:
            #- name: config-volume
              #mountPath: /var/www/html/LocalSettings.php
              #subPath: LocalSettings.php
          env:
            - name: MW_DB_HOST
              value: "mariadb-service"
            - name: MW_DB_NAME
              value: "mediawiki"
            - name: MW_DB_USER
              value: "root"
            - name: MW_DB_PASSWORD
              value: "secret"
            - name: MW_SERVER
              value: "http://mediawiki-service:80"
          ports:
            - containerPort: 80

---
# media-wiki-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31665
  selector:
    app: mediawiki

