# media-wiki-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
spec:
  selector:
    matchLabels:
      app: mediawiki
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      initContainers:
      - name: wait-for-1min
        image: busybox
        command: ['sh', '-c', 'sleep 20']
      containers:
        - name: mediawiki
          image: {{ .Values.mediawiki.image }}
          lifecycle:
            postStart:
              exec:
                command: 
                -  /bin/sh
                - -c
                - |
                  php ./maintenance/install.php --dbtype=mysql --dbserver=mariadb-service --dbname=wikidatabase --dbuser=root --dbpass=secret --dbport=3306 --server=http://localhost:31665 --scriptpath=/w --lang=en --pass=admin@123admin "twiki" admin
                  #tail -f /dev/null
          env:
            - name: MW_DB_HOST
              value: "mariadb-service"
            - name: MW_DB_NAME
              value: "mediawiki"
            - name: MW_DB_USER
              value: "root"
            - name: MW_DB_PASSWORD
              value: "secret"
            - name: MW_SERVER
              value: "http://mediawiki-service:80"
          ports:
            - containerPort: 80

---
# media-wiki-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31665
  selector:
    app: mediawiki

